# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  system.debyg: true

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- script: dotnet publish --configuration Release --output $(Build.ArtifactStagingDirectory)
  displayName: 'dotnet publish'

- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: $(Build.ArtifactStagingDirectory)
    includeRootFolder: false
    archiveType: zip
    archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
    replaceExistingArchive: true

# publish an artifact called drop
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
    artifactName: drop

# download the artifact drop from the previous job
- task: DownloadBuildArtifacts@0
  inputs:
    downloadPath: $(System.artifactsDirectory)
    artifactName: drop

# deploy to Azure Web App production
- task: AzureWebApp@1
  inputs:
    azureSubscription: cloudtestsubscription
    appName: wbaspdotnet
    package: $(System.artifactsDirectory)/drop/*.zip